# Generated by Django 5.2.17 on 2026-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=100, unique=True)),
                ('resource_name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(choices=[('VM', 'Virtual Machine'), ('CONTAINER', 'Container'), ('DATABASE', 'Database'), ('STORAGE', 'Storage'), ('NETWORK', 'Network'), ('SERVERLESS', 'Serverless Function')], default='VM', max_length=50)),
                ('cpu_usage', models.FloatField(default=0.0, help_text='CPU usage percentage (0-100)')),
                ('memory_usage', models.FloatField(default=0.0, help_text='Memory usage percentage (0-100)')),
                ('storage_usage', models.FloatField(default=0.0, help_text='Storage usage percentage (0-100)')),
                ('network_usage', models.FloatField(default=0.0, help_text='Network usage in Mbps')),
                ('status', models.CharField(choices=[('active', 'Active'), ('idle', 'Idle'), ('overloaded', 'Overloaded'), ('underutilized', 'Underutilized'), ('offline', 'Offline')], default='active', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'ordering': ['-timestamp'],
            },
        ),
    ]
