# Generated by Django 5.2.17 on 2026-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=100, unique=True)),
                ('resource_id', models.CharField(blank=True, default='', max_length=100)),
                ('alert_type', models.CharField(default='Telemetry Threshold Exceeded', max_length=150)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Warning', 'Warning'), ('Cost Alert', 'Cost Alert'), ('Optimization Alert', 'Optimization Alert'), ('Info', 'Info')], default='Warning', max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
    ]
