# Generated by Django 5.2.17 on 2026-08-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('resource_id', models.CharField(max_length=100)),
                ('resource_name', models.CharField(blank=True, default='', max_length=200)),
                ('prediction', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('recommendation', models.TextField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=50)),
                ('reason', models.TextField(blank=True, default='')),
                ('risk', models.TextField(blank=True, default='')),
                ('what_if', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Optimization Recommendation',
                'verbose_name_plural': 'Optimization Recommendations',
                'ordering': ['-updated_at'],
            },
        ),
    ]
