# Generated by Django 5.2.17 on 2026-08-19 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_optimizationrecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_identifier', models.CharField(db_index=True, max_length=100)),
                ('prediction', models.CharField(max_length=50)),
                ('confidence', models.FloatField(default=0.0)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('storage_usage', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_predictions', to='resources.resource')),
            ],
            options={
                'verbose_name': 'ML Prediction History',
                'verbose_name_plural': 'ML Prediction Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_identifier', models.CharField(db_index=True, max_length=100)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('storage_usage', models.FloatField(default=0.0)),
                ('network_usage', models.FloatField(default=0.0)),
                ('status', models.CharField(default='active', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_history', to='resources.resource')),
            ],
            options={
                'verbose_name': 'Resource Telemetry',
                'verbose_name_plural': 'Resource Telemetries',
                'ordering': ['-timestamp'],
            },
        ),
    ]
