# Generated by Django 5.2.17 on 2026-09-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_populate_cloudopt_records'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
